// <auto-generated />
namespace EKZ_BoolShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Initilize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initilize));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261915385_Initilize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
